# Configs for pwills.com

title: "Akmal"
name: "Akmal"
email: akmal@namal.edu.pk
url: "https://akmalds.github.io"
repository: "akmalds/akmalds.github.io"

include:
  - _pages
  - assets
  - index.html
exclude:
  - TODO.md
  - README.md
  - "*.org"
  - "*ltximg*"

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-include-cache

# Build settings
markdown: kramdown
theme: "minimal-mistakes-jekyll"
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dirt"
  
# settings for author profile
author:
  name   : "Akmal"
  avatar : ""
  bio    : "I enjoy writing about my practical experince. I'm interested in - mostly computing and maths."
  location: "Pakistan"
  github : akmalds
  linkedin: 
  email  : akmal@namal.edu.pk


# # comments by disqus
comments:
  provider: "disqus"
  disqus:
    shortname: ""

# analytics:
#   provider: "google-gtag"
#   google:
#     tracking_id: "UA-191032973-1"
#     anonymize_ip: false # default


# pagination for blog page
paginate: 10 # number of posts to show
paginate_path: /page:num/

# default YAML front matter
defaults:
  # all
  - scope:
      path: ""
    values:
      layout: single
      mathjax: true
      author_profile: true
      class: wide
      title: " "
      title_separator: "|"
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      author_profile: false
      excerpt: ""
      sidebar:
        nav: "portfolio"

# collections
collections:
  portfolio:
    output: true
